test_recursive: test_recursive.cpp RecursiveMultiplication.cpp RecursiveMultiplication.hpp Helper.cpp Helper.hpp
	g++ -Wall -g test_recursive.cpp RecursiveMultiplication.cpp Helper.cpp -o test_recursive

test_karatsuba: test_karatsuba.cpp KaratsubaMultiplication.cpp KaratsubaMultiplication.hpp Helper.cpp Helper.hpp
	g++ -Wall -g test_karatsuba.cpp KaratsubaMultiplication.cpp Helper.cpp -o test_karatsuba 

analyse_recursive: analyse_recursive.cpp RecursiveMultiplication.cpp RecursiveMultiplication.hpp Helper.cpp Helper.hpp
	g++ -Wall -g analyse_recursive.cpp RecursiveMultiplication.cpp Helper.cpp -o analyse_recursive

analyse_karatsuba: analyse_karatsuba.cpp KaratsubaMultiplication.cpp KaratsubaMultiplication.hpp Helper.cpp Helper.hpp
	g++ -Wall -g analyse_karatsuba.cpp KaratsubaMultiplication.cpp Helper.cpp -o analyse_karatsuba 
