insertion: InsertionSort.hpp InsertionSort.cpp test_insertion.cpp
	g++ -Wall -g InsertionSort.cpp test_insertion.cpp -o test_insertion

merge: MergeSort.hpp MergeSort.cpp test_merge.cpp
	g++ -Wall -g MergeSort.cpp test_merge.cpp -o test_merge
